// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU4AmK18lOFe1p_maUs4osWFjFuvAVrSo',
    appId: '1:277091199127:web:de6acbcc156dffbfca21d2',
    messagingSenderId: '277091199127',
    projectId: 'chave-d2009',
    authDomain: 'chave-d2009.firebaseapp.com',
    storageBucket: 'chave-d2009.appspot.com',
    measurementId: 'G-NNP27FD46E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVFRpyeRhEDaWThQi7Lh-Z63oSMnNH4o',
    appId: '1:277091199127:android:fec090efab4212f5ca21d2',
    messagingSenderId: '277091199127',
    projectId: 'chave-d2009',
    storageBucket: 'chave-d2009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzOEDhkhij0Fq_nw_nWY5K-GD7cXG2lR8',
    appId: '1:277091199127:ios:2eb6be289d1d1bf3ca21d2',
    messagingSenderId: '277091199127',
    projectId: 'chave-d2009',
    storageBucket: 'chave-d2009.appspot.com',
    iosClientId: '277091199127-3jicbf33s857e6ksvdpeg3oi6j1uu6d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzOEDhkhij0Fq_nw_nWY5K-GD7cXG2lR8',
    appId: '1:277091199127:ios:2eb6be289d1d1bf3ca21d2',
    messagingSenderId: '277091199127',
    projectId: 'chave-d2009',
    storageBucket: 'chave-d2009.appspot.com',
    iosClientId: '277091199127-3jicbf33s857e6ksvdpeg3oi6j1uu6d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chave',
  );
}
